# Generated by Django 6.0.2 on 2026-02-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна за добу (грн)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для оренди')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars_images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автомобіль',
                'verbose_name_plural': 'Автомобілі',
            },
        ),
    ]
