# Generated by Django 6.0.2 on 2026-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_booking_end_date_alter_booking_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Рік випуску'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Базова ціна за 24 години (грн)'),
        ),
    ]
