# Generated by Django 6.0.2 on 2026-03-31 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_year_alter_car_price_per_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_with_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Оплачено балами'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс кешбеку (грн)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Профіль клієнта',
                'verbose_name_plural': 'Профілі клієнтів',
            },
        ),
    ]
