# Generated by Django 6.0.2 on 2026-03-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_booking_paid_with_balance_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Витрачено за весь час'),
        ),
    ]
