# Generated by Django 6.0.2 on 2026-03-31 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_userprofile_total_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('discount_percent', models.IntegerField(default=5, verbose_name='Знижка (%)')),
                ('valid_until', models.DateTimeField(verbose_name='Дійсний до')),
                ('usage_limit', models.IntegerField(default=10, verbose_name='Ліміт використань')),
                ('current_uses', models.IntegerField(default=0, verbose_name='Використано разів')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Знижка промокоду'),
        ),
        migrations.AddField(
            model_name='booking',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.promocode', verbose_name='Промокод'),
        ),
    ]
