# Generated by Django 6.0.2 on 2026-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_promocode_booking_promo_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='trips_since_last_service',
            field=models.IntegerField(default=0, verbose_name='Поїздок після ТО'),
        ),
    ]
