# Generated by Django 6.0.2 on 2026-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_trips_since_last_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='documents_verified',
            field=models.BooleanField(default=False, verbose_name='Документи підтверджено'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='driving_experience',
            field=models.IntegerField(default=0, verbose_name='Стаж водіння (років)'),
        ),
    ]
