# Generated by Django 6.0.2 on 2026-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='documents_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифіковано (18+)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passports/', verbose_name='Фото паспорта'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата верифікації'),
        ),
    ]
